package com.idara.miniball;

import android.app.Activity;
import android.app.AlertDialog;
import android.os.Bundle;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import android.content.pm.ActivityInfo;

import java.net.*;
import java.util.*;

public class MainActivity extends Activity {
    private GameView gameView;
    private TextView statusText, scoreText, playersText, timerText;
    private EditText ipInput;
    private Button hostBtn, joinBtn, redTeamBtn, blueTeamBtn, settingsBtn;
    private int requestedTeam = 1;
    private int hostRedColor = Color.rgb(235, 70, 70);
    private int hostBlueColor = Color.rgb(70, 145, 255);
    private int matchMinutes = 5;
    private final int[] redPalette = new int[]{Color.rgb(235,70,70),Color.rgb(255,118,52),Color.rgb(222,60,110),Color.rgb(190,55,235),Color.rgb(245,205,45)};
    private final int[] bluePalette = new int[]{Color.rgb(70,145,255),Color.rgb(55,210,255),Color.rgb(80,210,130),Color.rgb(110,100,255),Color.rgb(245,245,245)};
    private int redColorIndex = 0, blueColorIndex = 0;

    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        FrameLayout root = new FrameLayout(this);
        root.setBackgroundColor(Color.rgb(8,10,14));
        buildCompactHud(root);
        gameView = new GameView(this, new GameView.HudListener() {
            @Override public void onStatus(final String s){ runOnUiThread(new Runnable(){@Override public void run(){ if(statusText!=null) statusText.setText(s); }}); }
            @Override public void onScore(final int r, final int b){ runOnUiThread(new Runnable(){@Override public void run(){ if(scoreText!=null) scoreText.setText(r+" - "+b); }}); }
            @Override public void onPlayers(final int c){ runOnUiThread(new Runnable(){@Override public void run(){ if(playersText!=null) playersText.setText("👥 "+c); }}); }
            @Override public void onTime(final int sec){ runOnUiThread(new Runnable(){@Override public void run(){ if(timerText!=null){ int m=Math.max(0,sec)/60; int s=Math.max(0,sec)%60; timerText.setText(String.format(Locale.US,"%02d:%02d",m,s)); } }}); }
        });
        gameView.setHostConfig(hostRedColor, hostBlueColor, matchMinutes);
        root.addView(gameView, 0, new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT));
        setContentView(root);
        hostBtn.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){ gameView.setHostConfig(hostRedColor,hostBlueColor,matchMinutes); gameView.startHost(); }});
        joinBtn.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){ gameView.startClient(ipInput.getText().toString().trim(), requestedTeam); }});
        redTeamBtn.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){ requestedTeam=0; updateTeamButtons(); }});
        blueTeamBtn.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){ requestedTeam=1; updateTeamButtons(); }});
        settingsBtn.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){ showHostSettingsDialog(); }});
        updateTeamButtons();
    }

    private void buildCompactHud(FrameLayout root){
        LinearLayout topHud = new LinearLayout(this); topHud.setOrientation(LinearLayout.HORIZONTAL); topHud.setGravity(Gravity.CENTER_VERTICAL); topHud.setPadding(dp(7),dp(4),dp(7),dp(4)); topHud.setBackgroundColor(Color.argb(105,10,13,18));
        hostBtn=makeMiniButton("H"); joinBtn=makeMiniButton("J");
        ipInput=new EditText(this); ipInput.setText("192.168.1."); ipInput.setHint("IP"); ipInput.setSingleLine(true); ipInput.setTextSize(12); ipInput.setTextColor(Color.WHITE); ipInput.setHintTextColor(Color.LTGRAY); ipInput.setInputType(InputType.TYPE_CLASS_TEXT); ipInput.setPadding(dp(8),0,dp(8),0); ipInput.setBackgroundColor(Color.argb(170,35,43,55));
        redTeamBtn=makeMiniButton("R"); blueTeamBtn=makeMiniButton("B"); settingsBtn=makeMiniButton("⚙");
        statusText=makeChipText("Ready",12,Gravity.CENTER_VERTICAL); playersText=makeChipText("👥 0",13,Gravity.CENTER); timerText=makeChipText("05:00",15,Gravity.CENTER); scoreText=makeChipText("0 - 0",22,Gravity.CENTER); scoreText.setTypeface(Typeface.DEFAULT_BOLD);
        topHud.addView(hostBtn,new LinearLayout.LayoutParams(dp(40),dp(36))); topHud.addView(joinBtn,new LinearLayout.LayoutParams(dp(40),dp(36))); topHud.addView(ipInput,new LinearLayout.LayoutParams(dp(125),dp(36))); topHud.addView(redTeamBtn,new LinearLayout.LayoutParams(dp(34),dp(36))); topHud.addView(blueTeamBtn,new LinearLayout.LayoutParams(dp(34),dp(36))); topHud.addView(settingsBtn,new LinearLayout.LayoutParams(dp(40),dp(36))); topHud.addView(statusText,new LinearLayout.LayoutParams(0,dp(36),1)); topHud.addView(playersText,new LinearLayout.LayoutParams(dp(70),dp(36))); topHud.addView(timerText,new LinearLayout.LayoutParams(dp(80),dp(36))); topHud.addView(scoreText,new LinearLayout.LayoutParams(dp(95),dp(36)));
        FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, dp(44)); params.gravity = Gravity.TOP; root.addView(topHud, params);
    }
    private TextView makeChipText(String text,int size,int gravity){ TextView t=new TextView(this); t.setText(text); t.setTextColor(Color.WHITE); t.setTextSize(size); t.setSingleLine(true); t.setGravity(gravity); t.setPadding(dp(6),0,dp(6),0); return t; }
    private Button makeMiniButton(String text){ Button b=new Button(this); b.setText(text); b.setTextColor(Color.WHITE); b.setTextSize(13); b.setAllCaps(false); b.setPadding(0,0,0,0); b.setBackgroundColor(Color.argb(210,45,115,245)); return b; }
    private void updateTeamButtons(){ redTeamBtn.setBackgroundColor(requestedTeam==0?Color.rgb(235,70,70):Color.argb(145,70,70,70)); blueTeamBtn.setBackgroundColor(requestedTeam==1?Color.rgb(70,145,255):Color.argb(145,70,70,70)); }
    private void showHostSettingsDialog(){
        final LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(22),dp(16),dp(22),dp(10));
        final TextView durationLabel=new TextView(this); durationLabel.setTextColor(Color.BLACK); durationLabel.setTextSize(18); durationLabel.setText("وقت المباراة: "+matchMinutes+" دقائق");
        SeekBar durationSeek=new SeekBar(this); durationSeek.setMax(10); durationSeek.setProgress(matchMinutes-5);
        Button redColorBtn=new Button(this); redColorBtn.setText("تغيير لون الفريق الأحمر"); redColorBtn.setTextColor(Color.WHITE); redColorBtn.setBackgroundColor(hostRedColor);
        Button blueColorBtn=new Button(this); blueColorBtn.setText("تغيير لون الفريق الأزرق"); blueColorBtn.setTextColor(Color.WHITE); blueColorBtn.setBackgroundColor(hostBlueColor);
        TextView hint=new TextView(this); hint.setText("هذه الإعدادات يختارها المضيف قبل HOST، ويمكن تغييرها أثناء اللعب."); hint.setTextSize(13); hint.setTextColor(Color.DKGRAY); hint.setPadding(0,dp(10),0,0);
        box.addView(durationLabel); box.addView(durationSeek); box.addView(redColorBtn,new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(46))); box.addView(blueColorBtn,new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(46))); box.addView(hint);
        durationSeek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){@Override public void onProgressChanged(SeekBar s,int p,boolean f){ matchMinutes=5+p; durationLabel.setText("وقت المباراة: "+matchMinutes+" دقائق"); if(gameView!=null) gameView.setHostConfig(hostRedColor,hostBlueColor,matchMinutes); } @Override public void onStartTrackingTouch(SeekBar s){} @Override public void onStopTrackingTouch(SeekBar s){} });
        redColorBtn.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){ redColorIndex=(redColorIndex+1)%redPalette.length; hostRedColor=redPalette[redColorIndex]; v.setBackgroundColor(hostRedColor); if(gameView!=null) gameView.setHostConfig(hostRedColor,hostBlueColor,matchMinutes); }});
        blueColorBtn.setOnClickListener(new View.OnClickListener(){@Override public void onClick(View v){ blueColorIndex=(blueColorIndex+1)%bluePalette.length; hostBlueColor=bluePalette[blueColorIndex]; v.setBackgroundColor(hostBlueColor); if(gameView!=null) gameView.setHostConfig(hostRedColor,hostBlueColor,matchMinutes); }});
        new AlertDialog.Builder(this).setTitle("إعدادات المضيف").setView(box).setPositiveButton("تم",null).show();
    }
    private int dp(int v){ return (int)(v*getResources().getDisplayMetrics().density+0.5f); }
    @Override protected void onDestroy(){ super.onDestroy(); if(gameView!=null){ gameView.stopNetwork(); gameView.stopGameLoop(); } }

    public static class GameView extends View implements Runnable{
        interface HudListener{ void onStatus(String s); void onScore(int r,int b); void onPlayers(int c); void onTime(int sec); }
        private static final int PORT=50005, MAX_PLAYERS=10, MAX_TEAM_PLAYERS=5;
        private final Activity activity; private final HudListener hud; private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); private final Object lock=new Object();
        private Thread gameThread, netThread; private boolean running=true; private DatagramSocket socket; private InetAddress remoteAddress; private int remotePort=PORT; private boolean isHost=false,isClient=false; private int localPlayerId=-1;
        private final Player[] players=new Player[MAX_PLAYERS]; private final HashMap<String,Integer> clientMap=new HashMap<>(); private Ball ball;
        private int redScore=0, blueScore=0; private float fieldW=1600f, fieldH=900f; private float touchStartX=-1,touchStartY=-1,joyX=0,joyY=0; private boolean touching=false;
        private RectF actionButton=new RectF(); private int actionTapCount=0; private long actionResolveTime=0; private int pendingActionCode=0; private long lastNetSend=0,lastHelloSend=0;
        private int carrierId=-1; private long lastTackleTime=0; private int redTeamColor=Color.rgb(235,70,70), blueTeamColor=Color.rgb(70,145,255); private int matchDurationMinutes=5; private long matchStartTime=0; private int lastSecondsLeft=300; private int requestedTeamForClient=1;
        public GameView(Activity a,HudListener h){ activity=a; hud=h; setFocusable(true); for(int i=0;i<MAX_PLAYERS;i++) players[i]=new Player(i); ball=new Ball(fieldW/2f,fieldH/2f,18); resetMatch(); gameThread=new Thread(this); gameThread.start(); hud.onStatus("H=HOST  J=JOIN  R/B=اختيار الفريق  ⚙=إعدادات"); hud.onScore(redScore,blueScore); hud.onPlayers(0); hud.onTime(lastSecondsLeft); }
        public void setHostConfig(int r,int b,int min){ synchronized(lock){ redTeamColor=r; blueTeamColor=b; matchDurationMinutes=Math.max(5,Math.min(15,min)); if(!isHost&&!isClient){ lastSecondsLeft=matchDurationMinutes*60; hud.onTime(lastSecondsLeft);} } }
        public void stopGameLoop(){ running=false; }
        public void startHost(){ stopNetwork(); synchronized(lock){ isHost=true; isClient=false; localPlayerId=0; clientMap.clear(); resetMatch(); players[0].active=true; players[0].isLocal=true; players[0].team=0; spawnPlayer(players[0]); matchStartTime=System.currentTimeMillis(); lastSecondsLeft=matchDurationMinutes*60; hud.onPlayers(getActivePlayerCount()); hud.onTime(lastSecondsLeft);} try{ socket=new DatagramSocket(PORT); socket.setReuseAddress(true); hud.onStatus("HOST IP: "+getLocalIpAddress()); startHostListener(); }catch(Exception e){ hud.onStatus("Host error: "+e.getMessage()); } }
        public void startClient(String hostIp,int requestedTeam){ stopNetwork(); if(hostIp==null||hostIp.length()<7){ hud.onStatus("اكتب IP الهاتف المضيف"); return;} synchronized(lock){ isHost=false; isClient=true; localPlayerId=-1; resetLocalClientState(); requestedTeamForClient=requestedTeam; } try{ socket=new DatagramSocket(); socket.setReuseAddress(true); remoteAddress=InetAddress.getByName(hostIp); remotePort=PORT; hud.onStatus("Connecting to "+hostIp+"..."); sendRaw("HELLO|"+requestedTeam); startClientListener(); }catch(Exception e){ hud.onStatus("Join error: "+e.getMessage()); } }
        public void stopNetwork(){ try{ if(socket!=null) socket.close(); }catch(Exception ignored){} socket=null; remoteAddress=null; remotePort=PORT; synchronized(lock){ isHost=false; isClient=false; localPlayerId=-1; clientMap.clear(); for(int i=0;i<MAX_PLAYERS;i++){ players[i].remoteKey=""; players[i].isLocal=false; } } }
        private void startHostListener(){ netThread=new Thread(new Runnable(){@Override public void run(){ byte[] buf=new byte[2048]; while(socket!=null&&!socket.isClosed()){ try{ DatagramPacket packet=new DatagramPacket(buf,buf.length); socket.receive(packet); String msg=new String(packet.getData(),0,packet.getLength()).trim(); String key=endpointKey(packet.getAddress(),packet.getPort()); if(msg.startsWith("HELLO")) handleHello(msg,packet.getAddress(),packet.getPort(),key); else if(msg.startsWith("INPUT|")) handleInput(msg,key); }catch(Exception e){ break; } } }}); netThread.start(); }
        private void handleHello(String msg,InetAddress address,int port,String key){ synchronized(lock){ Integer existing=clientMap.get(key); if(existing!=null){ sendWelcome(existing,address,port); return;} int req=1; String[] parts=msg.split("\\|"); if(parts.length>=2) req=safeInt(parts[1],1); req=req==0?0:1; int assigned=chooseAvailableTeam(req); if(assigned==-1){ sendRawTo("FULL",address,port); hud.onStatus("الغرفة ممتلئة"); return;} int newId=findFreePlayerSlot(); if(newId==-1){ sendRawTo("FULL",address,port); hud.onStatus("الغرفة ممتلئة"); return;} Player pl=players[newId]; pl.active=true; pl.isLocal=false; pl.remoteAddress=address; pl.remotePort=port; pl.remoteKey=key; pl.team=assigned; spawnPlayer(pl); clientMap.put(key,newId); sendWelcome(newId,address,port); hud.onStatus("Player "+(newId+1)+" connected"); hud.onPlayers(getActivePlayerCount()); sendStateToAll(); } }
        private int chooseAvailableTeam(int req){ int other=req==0?1:0; if(getTeamCount(req)<MAX_TEAM_PLAYERS) return req; if(getTeamCount(other)<MAX_TEAM_PLAYERS) return other; return -1; }
        private int getTeamCount(int team){ int c=0; for(int i=0;i<MAX_PLAYERS;i++) if(players[i].active&&players[i].team==team)c++; return c; }
        private void sendWelcome(int id,InetAddress address,int port){ int team=players[id].team; String msg="WELCOME|"+id+"|"+team+"|"+fieldW+"|"+fieldH+"|"+redTeamColor+"|"+blueTeamColor+"|"+matchDurationMinutes; sendRawTo(msg,address,port); }
        private int findFreePlayerSlot(){ for(int i=1;i<MAX_PLAYERS;i++) if(!players[i].active) return i; return -1; }
        private void handleInput(String msg,String key){ String[] s=msg.split("\\|"); if(s.length<4)return; synchronized(lock){ Integer idMap=clientMap.get(key); if(idMap==null)return; int id=safeInt(s[1],-1); if(id!=idMap||id<0||id>=MAX_PLAYERS)return; players[id].inputX=safeFloat(s[2],0); players[id].inputY=safeFloat(s[3],0); if(s.length>=5){ int code=safeInt(s[4],0); if(code>=1&&code<=3) players[id].actionCode=code; } players[id].lastPacketTime=System.currentTimeMillis(); } }
        private void startClientListener(){ netThread=new Thread(new Runnable(){@Override public void run(){ byte[] buf=new byte[8192]; while(socket!=null&&!socket.isClosed()){ try{ DatagramPacket packet=new DatagramPacket(buf,buf.length); socket.receive(packet); String msg=new String(packet.getData(),0,packet.getLength()).trim(); if(msg.startsWith("WELCOME|")) handleWelcome(msg); else if(msg.startsWith("STATE|")) applyState(msg); else if(msg.startsWith("FULL")) hud.onStatus("الغرفة ممتلئة"); }catch(Exception e){ break; } } }}); netThread.start(); }
        private void handleWelcome(String msg){ String[] s=msg.split("\\|"); if(s.length<5)return; synchronized(lock){ localPlayerId=safeInt(s[1],-1); int team=safeInt(s[2],1); if(s.length>=8){ redTeamColor=safeInt(s[5],redTeamColor); blueTeamColor=safeInt(s[6],blueTeamColor); matchDurationMinutes=safeInt(s[7],matchDurationMinutes); } if(localPlayerId>=0&&localPlayerId<MAX_PLAYERS){ players[localPlayerId].isLocal=true; players[localPlayerId].team=team; } hud.onStatus("Connected | Player "+(localPlayerId+1)+" | "+(team==0?"RED":"BLUE")); } }
        private void applyState(String msg){ String[] main=msg.split("\\|"); if(main.length<13)return; synchronized(lock){ redScore=safeInt(main[1],0); blueScore=safeInt(main[2],0); ball.x=safeFloat(main[3],fieldW/2f); ball.y=safeFloat(main[4],fieldH/2f); ball.vx=safeFloat(main[5],0); ball.vy=safeFloat(main[6],0); carrierId=safeInt(main[7],-1); redTeamColor=safeInt(main[8],redTeamColor); blueTeamColor=safeInt(main[9],blueTeamColor); lastSecondsLeft=safeInt(main[10],lastSecondsLeft); matchDurationMinutes=safeInt(main[11],matchDurationMinutes); for(int i=0;i<MAX_PLAYERS;i++) players[i].active=false; int count=safeInt(main[12],0); for(int i=0;i<count;i++){ int index=13+i; if(index>=main.length)break; String[] d=main[index].split(","); if(d.length<7)continue; int id=safeInt(d[0],-1); if(id<0||id>=MAX_PLAYERS)continue; Player pl=players[id]; pl.active=safeInt(d[1],0)==1; pl.team=safeInt(d[2],id%2); pl.x=safeFloat(d[3],pl.x); pl.y=safeFloat(d[4],pl.y); pl.vx=safeFloat(d[5],0); pl.vy=safeFloat(d[6],0); pl.isLocal=id==localPlayerId; } hud.onScore(redScore,blueScore); hud.onPlayers(getActivePlayerCount()); hud.onTime(lastSecondsLeft); } }
        private void sendStateToAll(){ if(!isHost||socket==null||socket.isClosed())return; String state=buildStateMessage(); for(int i=1;i<MAX_PLAYERS;i++){ Player pl=players[i]; if(pl.active&&pl.remoteAddress!=null) sendRawTo(state,pl.remoteAddress,pl.remotePort); } }
        private String buildStateMessage(){ StringBuilder sb=new StringBuilder(); sb.append("STATE|").append(redScore).append("|").append(blueScore).append("|").append(fmt(ball.x)).append("|").append(fmt(ball.y)).append("|").append(fmt(ball.vx)).append("|").append(fmt(ball.vy)).append("|").append(carrierId).append("|").append(redTeamColor).append("|").append(blueTeamColor).append("|").append(lastSecondsLeft).append("|").append(matchDurationMinutes).append("|"); int count=0; for(int i=0;i<MAX_PLAYERS;i++) if(players[i].active) count++; sb.append(count); for(int i=0;i<MAX_PLAYERS;i++){ Player pl=players[i]; if(!pl.active)continue; sb.append("|").append(pl.id).append(",").append(pl.active?1:0).append(",").append(pl.team).append(",").append(fmt(pl.x)).append(",").append(fmt(pl.y)).append(",").append(fmt(pl.vx)).append(",").append(fmt(pl.vy)); } return sb.toString(); }
        private void sendInput(){ if(!isClient||socket==null||socket.isClosed()||remoteAddress==null)return; if(localPlayerId<0){ long now=System.currentTimeMillis(); if(now-lastHelloSend>600){ lastHelloSend=now; sendRaw("HELLO|"+requestedTeamForClient);} return;} String msg; synchronized(lock){ int code=pendingActionCode; pendingActionCode=0; msg="INPUT|"+localPlayerId+"|"+fmt(joyX)+"|"+fmt(joyY)+"|"+code; } sendRaw(msg); }
        private void sendRaw(String msg){ try{ if(socket==null||socket.isClosed()||remoteAddress==null)return; byte[] data=msg.getBytes(); socket.send(new DatagramPacket(data,data.length,remoteAddress,remotePort)); }catch(Exception ignored){} }
        private void sendRawTo(String msg,InetAddress address,int port){ try{ if(socket==null||socket.isClosed()||address==null)return; byte[] data=msg.getBytes(); socket.send(new DatagramPacket(data,data.length,address,port)); }catch(Exception ignored){} }
        @Override public void run(){ long last=System.nanoTime(); while(running){ long now=System.nanoTime(); float dt=(now-last)/1000000000f; last=now; if(dt>0.033f)dt=0.033f; update(dt); postInvalidate(); try{ Thread.sleep(16); }catch(Exception ignored){} } }
        private void update(float dt){ synchronized(lock){ resolveActionTapIfReady(); if(localPlayerId>=0&&localPlayerId<MAX_PLAYERS){ players[localPlayerId].inputX=joyX; players[localPlayerId].inputY=joyY; if(pendingActionCode>0&&isHost){ players[localPlayerId].actionCode=pendingActionCode; pendingActionCode=0; } } if(isHost){ updateTimer(); updateHostGame(dt); long t=System.currentTimeMillis(); if(t-lastNetSend>20){ lastNetSend=t; sendStateToAll(); } }else if(isClient){ long t=System.currentTimeMillis(); if(t-lastNetSend>20){ lastNetSend=t; sendInput(); } } } }
        private void resolveActionTapIfReady(){ if(actionTapCount<=0)return; long now=System.currentTimeMillis(); if(now<actionResolveTime)return; if(actionTapCount==1){ pendingActionCode=1; hud.onStatus("PASS"); }else if(actionTapCount==2){ pendingActionCode=2; hud.onStatus("THROUGH PASS"); }else{ pendingActionCode=3; hud.onStatus("POWER SHOOT"); } actionTapCount=0; }
        private void updateTimer(){ if(matchStartTime<=0) matchStartTime=System.currentTimeMillis(); long elapsed=(System.currentTimeMillis()-matchStartTime)/1000; int total=matchDurationMinutes*60; int left=Math.max(0,total-(int)elapsed); if(left!=lastSecondsLeft){ lastSecondsLeft=left; hud.onTime(lastSecondsLeft); } if(left<=0){ hud.onStatus("انتهت المباراة"); matchStartTime=System.currentTimeMillis(); resetRound(); } }
        private void updateHostGame(float dt){ for(int i=0;i<MAX_PLAYERS;i++){ Player pl=players[i]; if(!pl.active)continue; applyPlayerInput(pl,dt); movePlayer(pl,dt); clampPlayer(pl); } applyDefenseTackles(); applyBallControlAndActions(); moveBall(dt); handleBallWallsAndGoals(); for(int i=0;i<MAX_PLAYERS;i++){ if(!players[i].active)continue; collidePlayerBall(players[i],ball); for(int j=i+1;j<MAX_PLAYERS;j++){ if(players[j].active) collidePlayerPlayer(players[i],players[j]); } } for(int i=0;i<MAX_PLAYERS;i++) players[i].actionCode=0; }
        private void applyPlayerInput(Player pl,float dt){ float accel=980f; pl.vx+=pl.inputX*accel*dt; pl.vy+=pl.inputY*accel*dt; float max=305f, sp=(float)Math.sqrt(pl.vx*pl.vx+pl.vy*pl.vy); if(sp>max){ pl.vx=pl.vx/sp*max; pl.vy=pl.vy/sp*max; } }
        private void movePlayer(Player pl,float dt){ pl.x+=pl.vx*dt; pl.y+=pl.vy*dt; pl.vx*=0.91f; pl.vy*=0.91f; }
        private void moveBall(float dt){ ball.x+=ball.vx*dt; ball.y+=ball.vy*dt; ball.vx*=0.993f; ball.vy*=0.993f; }
        private void clampPlayer(Player pl){ if(pl.x<pl.r){pl.x=pl.r;pl.vx*=-0.35f;} if(pl.x>fieldW-pl.r){pl.x=fieldW-pl.r;pl.vx*=-0.35f;} if(pl.y<pl.r){pl.y=pl.r;pl.vy*=-0.35f;} if(pl.y>fieldH-pl.r){pl.y=fieldH-pl.r;pl.vy*=-0.35f;} }
        private void handleBallWallsAndGoals(){ float goalTop=fieldH/2f-150f, goalBottom=fieldH/2f+150f; if(ball.y<ball.r){ball.y=ball.r;ball.vy*=-0.78f;carrierId=-1;} if(ball.y>fieldH-ball.r){ball.y=fieldH-ball.r;ball.vy*=-0.78f;carrierId=-1;} if(ball.x<ball.r){ if(ball.y>goalTop&&ball.y<goalBottom){ blueScore++; carrierId=-1; hud.onScore(redScore,blueScore); resetRound(); return; } else { ball.x=ball.r; ball.vx*=-0.78f; carrierId=-1; } } if(ball.x>fieldW-ball.r){ if(ball.y>goalTop&&ball.y<goalBottom){ redScore++; carrierId=-1; hud.onScore(redScore,blueScore); resetRound(); } else { ball.x=fieldW-ball.r; ball.vx*=-0.78f; carrierId=-1; } } }
        private void collidePlayerPlayer(Player a,Player b){ float dx=b.x-a.x,dy=b.y-a.y,dist=(float)Math.sqrt(dx*dx+dy*dy),min=a.r+b.r; if(dist>0&&dist<min){ float nx=dx/dist,ny=dy/dist,overlap=min-dist; a.x-=nx*overlap*0.5f; a.y-=ny*overlap*0.5f; b.x+=nx*overlap*0.5f; b.y+=ny*overlap*0.5f; float tx=-ny,ty=nx,dpTanA=a.vx*tx+a.vy*ty,dpTanB=b.vx*tx+b.vy*ty,dpNormA=a.vx*nx+a.vy*ny,dpNormB=b.vx*nx+b.vy*ny; a.vx=tx*dpTanA+nx*dpNormB*0.85f; a.vy=ty*dpTanA+ny*dpNormB*0.85f; b.vx=tx*dpTanB+nx*dpNormA*0.85f; b.vy=ty*dpTanB+ny*dpNormA*0.85f; } }
        private void collidePlayerBall(Player pl,Ball b){ float dx=b.x-pl.x,dy=b.y-pl.y,dist=(float)Math.sqrt(dx*dx+dy*dy),min=pl.r+b.r; if(dist>0&&dist<min){ float nx=dx/dist,ny=dy/dist,overlap=min-dist; b.x+=nx*overlap; b.y+=ny*overlap; float relVx=b.vx-pl.vx,relVy=b.vy-pl.vy,sep=relVx*nx+relVy*ny; if(sep<0){ b.vx-=1.75f*sep*nx; b.vy-=1.75f*sep*ny; } b.vx+=pl.vx*0.42f; b.vy+=pl.vy*0.42f; float max=680f,sp=(float)Math.sqrt(b.vx*b.vx+b.vy*b.vy); if(sp>max){ b.vx=b.vx/sp*max; b.vy=b.vy/sp*max; } } }
        private void applyDefenseTackles(){ if(carrierId<0||carrierId>=MAX_PLAYERS)return; Player carrier=players[carrierId]; if(!carrier.active){ carrierId=-1; return;} long now=System.currentTimeMillis(); if(now-lastTackleTime<220)return; for(int i=0;i<MAX_PLAYERS;i++){ Player d=players[i]; if(!d.active||d.id==carrier.id||d.team==carrier.team)continue; float dx=d.x-carrier.x,dy=d.y-carrier.y,dist=(float)Math.sqrt(dx*dx+dy*dy),tackleDistance=d.r+carrier.r+7f; if(dist<tackleDistance){ float ds=(float)Math.sqrt(d.vx*d.vx+d.vy*d.vy),cs=(float)Math.sqrt(carrier.vx*carrier.vx+carrier.vy*carrier.vy); if(ds>80f||ds>cs*0.65f){ float nx,ny; if(dist>1f){nx=dx/dist;ny=dy/dist;}else{nx=d.team==0?1f:-1f;ny=0f;} carrierId=d.id; lastTackleTime=now; ball.x=d.x-nx*(d.r+ball.r+4f); ball.y=d.y-ny*(d.r+ball.r+4f); ball.vx=d.vx*0.85f-nx*180f; ball.vy=d.vy*0.85f-ny*180f; hud.onStatus("TACKLE! Player "+(d.id+1)); return; } } } }
        private void applyBallControlAndActions(){ Player c; if(carrierId>=0&&carrierId<MAX_PLAYERS&&players[carrierId].active){ c=players[carrierId]; float dx=ball.x-c.x,dy=ball.y-c.y,dist=(float)Math.sqrt(dx*dx+dy*dy); if(dist>95f){ carrierId=-1; c=getClosestPlayerToBall(60f); } }else{ c=getClosestPlayerToBall(60f); if(c!=null) carrierId=c.id; } if(c==null)return; int action=c.actionCode; if(action==1){ passToTeammate(c); carrierId=-1; return;} if(action==2){ decisiveThroughPass(c); carrierId=-1; return;} if(action>=3){ shootToGoal(c,900f); carrierId=-1; return;} float inputLen=(float)Math.sqrt(c.inputX*c.inputX+c.inputY*c.inputY),dirX,dirY; if(inputLen>0.15f){dirX=c.inputX/inputLen;dirY=c.inputY/inputLen;}else{ float vx=c.vx,vy=c.vy,vLen=(float)Math.sqrt(vx*vx+vy*vy); if(vLen>5f){dirX=vx/vLen;dirY=vy/vLen;}else{dirX=c.team==0?1f:-1f;dirY=0f;} } if(inputLen>0.08f){ float tx=c.x+dirX*(c.r+ball.r+5f),ty=c.y+dirY*(c.r+ball.r+5f); ball.x+=(tx-ball.x)*0.24f; ball.y+=(ty-ball.y)*0.24f; ball.vx=c.vx+dirX*85f; ball.vy=c.vy+dirY*85f; } }
        private Player getClosestPlayerToBall(float maxDist){ Player best=null; float bestDist=maxDist; for(int i=0;i<MAX_PLAYERS;i++){ Player pl=players[i]; if(!pl.active)continue; float dx=ball.x-pl.x,dy=ball.y-pl.y,dist=(float)Math.sqrt(dx*dx+dy*dy); if(dist<bestDist){bestDist=dist;best=pl;} } return best; }
        private void passToTeammate(Player from){ Player target=findNearestTeammate(from); if(target==null){ shootForward(from,500f); return;} float dx=target.x-ball.x,dy=target.y-ball.y,len=(float)Math.sqrt(dx*dx+dy*dy); if(len<1f)return; ball.vx=dx/len*540f; ball.vy=dy/len*540f; }
        private void decisiveThroughPass(Player from){ Player target=findBestForwardTeammate(from); if(target==null){ shootForward(from,650f); return;} float forward=from.team==0?170f:-170f,targetX=target.x+forward,targetY=target.y+target.vy*0.25f; if(targetX<80f)targetX=80f; if(targetX>fieldW-80f)targetX=fieldW-80f; if(targetY<80f)targetY=80f; if(targetY>fieldH-80f)targetY=fieldH-80f; float dx=targetX-ball.x,dy=targetY-ball.y,len=(float)Math.sqrt(dx*dx+dy*dy); if(len<1f)return; ball.vx=dx/len*700f; ball.vy=dy/len*700f; }
        private Player findNearestTeammate(Player from){ Player target=null; float best=999999f; for(int i=0;i<MAX_PLAYERS;i++){ Player pl=players[i]; if(!pl.active||pl.id==from.id||pl.team!=from.team)continue; float dx=pl.x-from.x,dy=pl.y-from.y,dist=(float)Math.sqrt(dx*dx+dy*dy); if(dist<best){best=dist;target=pl;} } return target; }
        private Player findBestForwardTeammate(Player from){ Player target=null; float best=-999999f; for(int i=0;i<MAX_PLAYERS;i++){ Player pl=players[i]; if(!pl.active||pl.id==from.id||pl.team!=from.team)continue; float progress=from.team==0?pl.x:fieldW-pl.x; float score=progress-Math.abs(pl.y-from.y)*0.35f; if(score>best){best=score;target=pl;} } return target; }
        private void shootToGoal(Player from,float power){ float goalX=from.team==0?fieldW+80f:-80f,goalY=fieldH/2f,dx=goalX-ball.x,dy=goalY-ball.y,len=(float)Math.sqrt(dx*dx+dy*dy); if(len<1f)return; ball.vx=dx/len*power; ball.vy=dy/len*power; }
        private void shootForward(Player from,float power){ float len=(float)Math.sqrt(from.inputX*from.inputX+from.inputY*from.inputY),dx,dy; if(len>0.15f){dx=from.inputX/len;dy=from.inputY/len;}else{dx=from.team==0?1f:-1f;dy=0f;} ball.vx=dx*power; ball.vy=dy*power; }
        private void resetLocalClientState(){ carrierId=-1; for(int i=0;i<MAX_PLAYERS;i++){ players[i].active=false; players[i].isLocal=false; players[i].inputX=0; players[i].inputY=0; players[i].actionCode=0; } ball.x=fieldW/2f; ball.y=fieldH/2f; ball.vx=0; ball.vy=0; }
        private void resetMatch(){ redScore=0; blueScore=0; carrierId=-1; matchStartTime=System.currentTimeMillis(); lastSecondsLeft=matchDurationMinutes*60; for(int i=0;i<MAX_PLAYERS;i++){ players[i].active=false; players[i].isLocal=false; players[i].inputX=0; players[i].inputY=0; players[i].actionCode=0; players[i].team=i%2; } resetRound(); hud.onScore(redScore,blueScore); hud.onTime(lastSecondsLeft); }
        private void resetRound(){ carrierId=-1; ball.x=fieldW/2f; ball.y=fieldH/2f; ball.vx=0; ball.vy=0; for(int i=0;i<MAX_PLAYERS;i++) if(players[i].active) spawnPlayer(players[i]); }
        private void spawnPlayer(Player pl){ int teamIndex=getTeamIndexForSpawn(pl); float gap=92f; if(pl.team==0){ pl.x=240f+teamIndex*58f; pl.y=fieldH/2f-185f+teamIndex*gap; }else{ pl.x=fieldW-240f-teamIndex*58f; pl.y=fieldH/2f-185f+teamIndex*gap; } if(pl.y<90f)pl.y=90f; if(pl.y>fieldH-90f)pl.y=fieldH-90f; pl.vx=0; pl.vy=0; pl.inputX=0; pl.inputY=0; pl.actionCode=0; }
        private int getTeamIndexForSpawn(Player target){ int index=0; for(int i=0;i<MAX_PLAYERS;i++){ if(players[i].active&&players[i].team==target.team){ if(players[i].id==target.id)return index; index++; } } return index; }
        @Override protected void onDraw(Canvas c){ super.onDraw(c); float screenW=getWidth(),screenH=getHeight(); float scale=Math.max(screenW/fieldW,screenH/fieldH); float ox=(screenW-fieldW*scale)/2f,oy=(screenH-fieldH*scale)/2f; c.drawColor(Color.rgb(10,12,15)); c.save(); c.translate(ox,oy); c.scale(scale,scale); drawField(c); drawPlayersAndBall(c); c.restore(); drawJoystick(c); drawActionButton(c); drawLocalPlayerInfo(c); }
        private void drawField(Canvas c){ p.setStyle(Paint.Style.FILL); float stripeW=fieldW/10f; for(int i=0;i<10;i++){ p.setColor(i%2==0?Color.rgb(64,165,76):Color.rgb(82,190,90)); c.drawRect(i*stripeW,0,(i+1)*stripeW,fieldH,p); } p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(8); p.setColor(Color.rgb(245,245,245)); c.drawRect(4,4,fieldW-4,fieldH-4,p); p.setStrokeWidth(5); p.setColor(Color.argb(220,255,255,255)); c.drawLine(fieldW/2f,4,fieldW/2f,fieldH-4,p); c.drawCircle(fieldW/2f,fieldH/2f,115,p); p.setStyle(Paint.Style.FILL); p.setColor(Color.WHITE); c.drawCircle(fieldW/2f,fieldH/2f,7,p); float goalTop=fieldH/2f-150f,goalBottom=fieldH/2f+150f; p.setStyle(Paint.Style.FILL); p.setColor(Color.rgb(25,31,39)); c.drawRect(0,goalTop,22,goalBottom,p); c.drawRect(fieldW-22,goalTop,fieldW,goalBottom,p); p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(8); p.setColor(Color.WHITE); c.drawLine(4,goalTop,4,goalBottom,p); c.drawLine(fieldW-4,goalTop,fieldW-4,goalBottom,p); p.setStrokeWidth(4); p.setColor(Color.argb(200,255,255,255)); c.drawRect(4,fieldH/2f-210f,210,fieldH/2f+210f,p); c.drawRect(fieldW-210,fieldH/2f-210f,fieldW-4,fieldH/2f+210f,p); }
        private void drawPlayersAndBall(Canvas c){ synchronized(lock){ for(int i=0;i<MAX_PLAYERS;i++) if(players[i].active) drawPlayer(c,players[i]); p.setStyle(Paint.Style.FILL); p.setColor(Color.WHITE); c.drawCircle(ball.x,ball.y,ball.r,p); p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(3); p.setColor(Color.rgb(35,35,35)); c.drawCircle(ball.x,ball.y,ball.r,p); } }
        private void drawPlayer(Canvas c,Player pl){ int color=pl.team==0?redTeamColor:blueTeamColor; p.setStyle(Paint.Style.FILL); p.setColor(Color.argb(75,0,0,0)); c.drawCircle(pl.x+5,pl.y+6,pl.r+3,p); p.setColor(color); c.drawCircle(pl.x,pl.y,pl.r,p); p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(pl.isLocal?6:3); p.setColor(pl.id==carrierId?Color.rgb(255,230,35):(pl.isLocal?Color.YELLOW:Color.WHITE)); c.drawCircle(pl.x,pl.y,pl.r,p); if(pl.id==carrierId){ p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(3); p.setColor(Color.argb(220,255,230,35)); c.drawCircle(pl.x,pl.y,pl.r+9,p); } p.setStyle(Paint.Style.FILL); p.setTextAlign(Paint.Align.CENTER); p.setTypeface(Typeface.DEFAULT_BOLD); p.setTextSize(24); p.setColor(Color.WHITE); c.drawText(String.valueOf(pl.id+1),pl.x,pl.y+8,p); }
        private void drawJoystick(Canvas c){ if(!touching)return; p.setStyle(Paint.Style.FILL); p.setColor(Color.argb(65,255,255,255)); c.drawCircle(touchStartX,touchStartY,62,p); p.setColor(Color.argb(165,255,255,255)); c.drawCircle(touchStartX+joyX*48,touchStartY+joyY*48,25,p); }
        private void drawActionButton(Canvas c){ float w=getWidth(),h=getHeight(),size=116f; actionButton.set(w-size-28f,h-size-32f,w-28f,h-32f); p.setStyle(Paint.Style.FILL); p.setColor(Color.argb(188,255,178,34)); c.drawOval(actionButton,p); p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(5); p.setColor(Color.WHITE); c.drawOval(actionButton,p); p.setStyle(Paint.Style.FILL); p.setTypeface(Typeface.DEFAULT_BOLD); p.setTextAlign(Paint.Align.CENTER); p.setTextSize(21); p.setColor(Color.WHITE); c.drawText("ACTION",actionButton.centerX(),actionButton.centerY()-8,p); p.setTextSize(13); c.drawText("1 PASS  2 THROUGH  3 SHOOT",actionButton.centerX(),actionButton.centerY()+18,p); }
        private void drawLocalPlayerInfo(Canvas c){ p.setStyle(Paint.Style.FILL); p.setTextAlign(Paint.Align.LEFT); p.setTypeface(Typeface.DEFAULT_BOLD); p.setTextSize(24); p.setColor(Color.argb(230,255,255,255)); String text; if(isHost) text="Player 1 / RED / HOST"; else if(isClient&&localPlayerId>=0){ String team=players[localPlayerId].team==0?"RED":"BLUE"; text="Player "+(localPlayerId+1)+" / "+team; }else if(isClient) text="Connecting..."; else text="H HOST | J JOIN | R/B choose team"; c.drawText(text,16,getHeight()-18,p); }
        @Override public boolean onTouchEvent(MotionEvent e){ int action=e.getActionMasked(); float x=e.getX(),y=e.getY(); if(action==MotionEvent.ACTION_DOWN){ if(actionButton.contains(x,y)){ registerActionTap(); return true;} touching=true; touchStartX=x; touchStartY=y; joyX=0; joyY=0; return true; } if(action==MotionEvent.ACTION_MOVE){ if(!touching)return true; float dx=x-touchStartX,dy=y-touchStartY,len=(float)Math.sqrt(dx*dx+dy*dy),max=78f; if(len>max){ dx=dx/len*max; dy=dy/len*max; } joyX=dx/max; joyY=dy/max; return true; } if(action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_CANCEL){ touching=false; joyX=0; joyY=0; return true; } return true; }
        private void registerActionTap(){ long now=System.currentTimeMillis(); if(now>actionResolveTime) actionTapCount=0; actionTapCount++; if(actionTapCount>3) actionTapCount=3; actionResolveTime=now+260; }
        private int getActivePlayerCount(){ int c=0; for(int i=0;i<MAX_PLAYERS;i++) if(players[i].active)c++; return c; }
        private String endpointKey(InetAddress a,int port){ return a.getHostAddress()+":"+port; }
        private String fmt(float v){ return String.format(Locale.US,"%.2f",v); }
        private int safeInt(String v,int f){ try{return Integer.parseInt(v);}catch(Exception e){return f;} }
        private float safeFloat(String v,float f){ try{return Float.parseFloat(v);}catch(Exception e){return f;} }
        private String getLocalIpAddress(){ try{ Enumeration<NetworkInterface> interfaces=NetworkInterface.getNetworkInterfaces(); while(interfaces.hasMoreElements()){ NetworkInterface intf=interfaces.nextElement(); Enumeration<InetAddress> addresses=intf.getInetAddresses(); while(addresses.hasMoreElements()){ InetAddress addr=addresses.nextElement(); if(!addr.isLoopbackAddress()&&addr instanceof Inet4Address) return addr.getHostAddress(); } } }catch(Exception ignored){} return "Unknown"; }
        private static class Player{ int id,team; boolean active=false,isLocal=false; float x=0,y=0,vx=0,vy=0,r=27,inputX=0,inputY=0; int actionCode=0; InetAddress remoteAddress; int remotePort; String remoteKey=""; long lastPacketTime=0; Player(int id){this.id=id;this.team=id%2;} }
        private static class Ball{ float x,y,vx,vy,r; Ball(float x,float y,float r){this.x=x;this.y=y;this.r=r;} }
    }
}
